module.exports = {
    CHANGE_STATUS_SUCCESS         : "Thay đổi status thành công!.",
    UPDATE_SUCCESS                : "Cập nhât thành công!.",
    UPDATE_ORDERING_SUCCESS       : "Cập nhật Ordering thành công!.",
    ADD_SUCCESS                   : "Thêm mới thành công!.",
    DELETE_SUCCESS                : "Xóa thành công!.",
    ALERT_BULK_ACTION             : "Vui lòng chọn click vào ô muốn thay đổi và chọn các option.",
    CHANGE_MULTI_STATUS_SUCCESS   : "%d thay đổi phần tử thành công!.",
    CHANGE_GROUPS_SUCCESS         : "Thay đổi trạng thái Group thành công!.",
    CHANGE_CATEGORY_SUCCESS       : "Thay đổi Category thành công!.",
    CHANGE_SPACECIALS_SUCCESS     : "Thay đổi Spacecial thành công!.",
    CHANGE_MULTI_ORDERING_SUCCESS : "%d phần tử thanh đổi Ordering thành công!.",
    CHANGE_MULTI_SPACECIAL_SUCCESS: "%d phần tử thanh đổi Spacecial thành công!.",
    DELETE_MULTI_SUCCESS          : "%d phần tử đã được xóa thành công!.",
    ERROR_NAME                    : 'Chiều dài từ %d đến %d ký tự.',
    ERROR_ORDERING                : 'Phải là số nguyên lớn hơn %d và bé hơn %d',
    ERROR_STATUS                  : 'Phải là một giá trị khác rỗng.',
    ERROR_SPECIAL                 : 'Phải là một giá trị khác rỗng.',
    ERROR_GROUP                   : 'Phải là một giá trị khác rỗng.',
    ERROR_GROUPACP                : 'Phải là một giá trị khác rỗng.',
    ERROR_FILE_REQUIRE            : 'Vui lòng chọn file upload.',
    ERROR_FILE_LIMIT              : 'Kích thước file lớn hơn %dMB.',
    LIMIT_UNEXPECTED_FILE_IMG     : 'dung lượng ảnh lớn hơn %dMB hoặc file upload không phải là hình ảnh.',
    ERROR_FILE_EXTENSION_IMG      : 'file upload không phải là hình ảnh.',
   
};
